@startuml UC10_ConsultarAgenda

skinparam backgroundColor #FAFAFA
skinparam ArrowColor #555555
skinparam SequenceLifeLineBorderColor #333333

actor "Funcionário" as Funcionario
participant "Sistema" as Sistema
database "Banco de Dados" as BD

Funcionario -> Sistema : consultarAgenda(funcionarioId, data)
activate Sistema

Sistema -> BD : buscarAtendimentos(funcionarioId, data)
activate BD

BD --> Sistema : listaAtendimentos
deactivate BD

alt Existem atendimentos

    Sistema --> Funcionario : exibirAgenda(listaAtendimentos)

else Nenhum atendimento encontrado

    Sistema --> Funcionario : exibirMensagem(\n"Nenhum atendimento encontrado")

end

deactivate Sistema

@enduml