@startuml DudaSpa_CasosDeUso

left to right direction
skinparam packageStyle rectangle
skinparam backgroundColor #FAFAFA
skinparam ArrowColor #555555
skinparam ActorBorderColor #333333

actor "Usuário" as Usuario
actor "Cliente" as Cliente
actor "Funcionário" as Funcionario
actor "Recepcionista" as Recepcionista
actor "Gerente" as Gerente

Usuario <|-- Cliente
Usuario <|-- Funcionario
Usuario <|-- Recepcionista
Usuario <|-- Gerente

rectangle "Sistema Duda Spa" {

  package "Conta e Acesso" {

    usecase "UC-01\nGerenciar Conta" as UC01
    usecase "UC-02\nFazer Login" as UC02
    usecase "UC-03\nRecuperar Senha" as UC03

  }

  package "Área do Cliente" {
    usecase "UC-04\nVisualizar Serviços e Promoções" as UC04
    usecase "UC-05\nVisualizar Profissionais" as UC05
    usecase "UC-06\nConsultar Horários Disponíveis" as UC06
    usecase "UC-07\nRealizar Agendamento" as UC07
    usecase "UC-08\nCancelar Agendamento" as UC08
    usecase "UC-09\nConsultar Histórico de Atendimentos" as UC09

  }

  package "Área do Funcionário" {

    usecase "UC-10\nConsultar Agenda de Atendimentos" as UC10
    usecase "UC-11\nRegistrar Evolução do Cliente" as UC11
    usecase "UC-12\nVisualizar Dados do Cliente" as UC12
    usecase "UC-13\nLançar Comissões" as UC13

  }

  package "Área da Recepcionista" {

    usecase "UC-14\nCadastrar Cliente" as UC14
    usecase "UC-15\nGerenciar Agendamentos da Equipe" as UC15
    usecase "UC-16\nLocalizar Agendamento do Cliente" as UC16
    usecase "UC-17\nRealizar Check-in" as UC17
    usecase "UC-18\nRegistrar Pagamento" as UC18

  }

  package "Área do Gerente" {

    usecase "UC-19\nAcompanhar Relatórios Financeiros" as UC19
    usecase "UC-20\nControlar Estoque de Produtos" as UC20
    usecase "UC-21\nGerenciar Serviços" as UC21
    usecase "UC-22\nGerenciar Promoções" as UC22

  }

}

Usuario --> UC01
Usuario --> UC02
Usuario --> UC03

Cliente --> UC04
Cliente --> UC05
Cliente --> UC06
Cliente --> UC07
Cliente --> UC08
Cliente --> UC09

Funcionario --> UC10
Funcionario --> UC11
Funcionario --> UC12
Funcionario --> UC13

Recepcionista --> UC14
Recepcionista --> UC15
Recepcionista --> UC16
Recepcionista --> UC17
Recepcionista --> UC18

Gerente --> UC19
Gerente --> UC20
Gerente --> UC21
Gerente --> UC22



UC07 ..> UC06 : <<include>>
UC17 ..> UC16 : <<include>>
UC18 ..> UC16 : <<include>>

UC03 ..> UC02 : <<extend>>
UC08 ..> UC07 : <<extend>>

@enduml